export const LOG_IN= 'LOG_IN'
export const LOG_OUT= 'LOG_OUT'
export const SEND_POLLS= 'SEND_POLLS'
export const REGISTER= 'REGISTER'
export const FIND_USER= 'FIND_USER'
export const DELETE_USER= 'DELETE_USER'
export const GET_USERS= 'GET_USERS'
export const GET_POLLS= 'GET_POLLS'
export const SET_INFO= 'SET_INFO'
export const SET_INFO_ADMIN= 'SET_INFO_ADMIN'
export const UPDATE_POLLS= 'UPDATE_POLLS'
export const GET_VOIVODESHIPS= 'GET_VOIVODESHIPS'

